export const types = {
    fire: { bg: 'linear-gradient(#f7c757,#d44646 80%)', font: '#fff', trad: 'Fuego' },
    water: { bg: 'linear-gradient(#a5cff0,#4996d1)', font: '#fff', trad: 'Agua' },
    grass: { bg: 'linear-gradient( #add19b,#5d9c3e )', font: '#fff', trad: 'Planta' },
    ground: { bg: 'linear-gradient(#EBD69D,#927D44)', font: '#fff', trad: 'Tierra' },
    rock: { bg: 'linear-gradient(#B8A038,#786824)', font: '#fff', trad: 'Roca' },
    normal: { bg: 'linear-gradient( #C6C6A7,#A8A878 )', font: '#fff', trad: 'Normal' },
    psychic: { bg: 'linear-gradient( #FA92B2,#F85888 )', font: '#fff', trad: 'Psìquico' },
    poison: { bg: 'linear-gradient( #C183C1,#A040A0 )', font: '#fff', trad: 'Veneno' },
    ghost: { bg: 'linear-gradient( #A292BC,#705898 )', font: '#fff', trad: 'Fantasma' },
    dragon: { bg: 'linear-gradient( #A27DFA,#7038F8 )', font: '#fff', trad: 'Dragon' },
    electric: { bg: 'linear-gradient( #FAE078,#F8D030 )', font: '#000', trad: 'Eléctrico' },
    steel: { bg: 'linear-gradient( #D1D1E0,#B8B8D0 )', font: '#000', trad: 'Acero' },
    fairy: { bg: 'linear-gradient( #F4BDC9,#EE99AC )', font: '#fff', trad: 'Hada' },
    fighting: { bg: 'linear-gradient(#D67873,#C03028)', font: '#fff', trad: 'Lucha' },
    bug: { bg: 'linear-gradient( #ebf0c5, #A8B820 )', font: '#000', trad: 'Bicho' },
    ice: { bg: 'linear-gradient(#fff,#9feef5 80%)', font: '#000', trad: 'Hielo' },
    dark: { bg: 'linear-gradient(#141414,#787878)', font: '#fff', trad: 'Siniestro' },
    flying: { bg: 'linear-gradient( #C6B7F5,#A890F0 )', font: '#fff', trad: 'Volador' },
};

export const typesStrenght = {
    normal: [ 'none' ],
    fighting: [ 'normal', 'rock', 'steel', 'ice', 'dark' ],
    flying: [ 'fighting', 'bug', 'grass' ],
    poison: [ 'grass', 'fairy' ],
    ground: [ 'poison', 'rock', 'steel', 'fire', 'electric' ],
    rock: [ 'flying', 'bug', 'fire', 'ice' ],
    bug: [ 'grass', 'psychic', 'dark' ],
    ghost: [ 'ghost', 'psychic' ],
    steel: [ 'rock', 'ice', 'fairy' ],
    fire: [ 'bug', 'steel', 'grass', 'ice' ],
    water: [ 'ground', 'rock', 'fire' ],
    grass: [ 'water', 'rock', 'ground' ],
    electric: [ 'flying', 'water' ],
    psychic: [ 'fighting', 'poison' ],
    ice: [ 'flying', 'ground', 'grass', 'dragon' ],
    dragon: [ 'dragon' ],
    fairy: [ 'fighting', 'dragon', 'dark' ],
    dark: [ 'ghost', 'psychic' ],
};

export const typesWeakness = {
    normal: [ 'fighting' ],
    fighting: [ 'flying', 'psychic', 'fairy' ],
    flying: [ 'rock', 'electric', 'ice' ],
    poison: [ 'ground', 'psychic' ],
    ground: [ 'water', 'grass', 'ice' ],
    rock: [ 'fighting', 'ground', 'steel', 'water', 'grass' ],
    bug: [ 'flying', 'rock', 'fire' ],
    ghost: [ 'dark', 'ghost' ],
    steel: [ 'fighting', 'ground', 'fire' ],
    fire: [ 'ground', 'rock', 'water' ],
    water: [ 'grass', 'electric' ],
    grass: [ 'poison', 'bug', 'flying', 'fire', 'ice' ],
    electric: [ 'ground' ],
    psychic: [ 'bug', 'ghost', 'dark' ],
    ice: [ 'fighting', 'rock', 'steel', 'fire' ],
    dragon: [ 'ice', 'dragon', 'fairy' ],
    fairy: [ 'poison', 'steel' ],
    dark: [ 'fighting', 'bug', 'fairy' ],
    // ...
};

export const generations = {
    'generation-i': 1,
    'generation-ii': 2,
    'generation-iii': 3,
    'generation-iv': 4,
    'generation-v': 5,
    'generation-vi': 6,
    'generation-vii': 7,
    'generation-viii': 8,
    'generation-ix': 9,
    'generation-x': 10,

}