# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

jobs: 
  vpscopy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: copy to vps server
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22,
          source: "."
          target: "./poke-app"

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    needs: vpscopy

    steps:
      - name: Remote ssh execution
      - uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script:
            docker container rm -f poke-app_pokeapp_1
            docker image rm -f poke-app_pokeapp
            docker-compose up -d

